[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/Sitemap.xml"
  status = 200

[[redirects]]
  from = "/news/:slug"
  to = "/news/view.html?slug=:slug"
  status = 200


